### PR TITLE
Rewrite with Awesome Style (and more descriptions)

### PR DESCRIPTION
**Pull request by loicreynier**
Rewrite the list with an "Awesome list style" with a table of content as proposed in #37 and more detailed descriptions.

The goal is to have the Markdown code checked by [`awesome-lint`](https://github.com/sindresorhus/awesome-lint) which is useful to insure a coherent style and verify links (URLs and ToC entries). Currently, only the audio section has been rewritten. All the audio-related subsections have been moved to this section. If this style is suitable , I will continue the rewrite of the other sections. 

Due to the longer descriptions, languages/libraries tags are highlighted with inline code. As an example, the Lollypop list entry now renders as follows:

- [Lollypop](https://gitlab.gnome.org/World/lollypop) - Lightweight modern music player designed to work excellently on the GNOME desktop environment with party mode, metadata fetching, MTP device sync and scrobbling `#python` `#libhandy`.

The rendered README can be properly viewed [here](https://github.com/loicreynier/awesome-gtk/blob/feat-rewrite-awesome-style/README.md).

### CODE REVIEW

**Comment by valpackett** [comment]
nice! It would be cool to add the linter to CI then

**Comment by loicreynier** [comment]
@valpackett I finished the rewrite, let me know what you think about it. You can preview it [here](https://github.com/loicreynier/awesome-gtk/blob/feat-rewrite-awesome-style/README.md).

I added a workflow with `awesome-lint` and the `typos` checker. The repository should have `awesome` and `awesome-list` as GitHub topic to remove the some linting errors.

**Comment by knuxbbs** [comment]
Will this be merged with the main branch?

**Comment by valpackett** [comment]
Woah, sorry, I completely missed the "finished" comment! Yeah, please pull in all the new additions from the main branch and go ahead @loicreynier :)

**Pull request merged**
